Models/ErrorViewModel.cs
namespace WebAR_Avatars.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AvatarController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebAR_Avatars.Models;

namespace WebAR_Avatars.Controllers
{
    public class AvatarController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult PlayerLoadScreen([Bind("avatar_url")] string avatar_url)
        {
            TempData["Avatar_src"] = avatar_url;
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Load([Bind("avatar_url")] string avatar_url)
        {
            TempData["Avatar_src"] = avatar_url;
            return View();
        }

        public IActionResult LoadAvatar()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebAR_Avatars.Models;

namespace WebAR_Avatars.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "How it Works";

            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Avatar/Create.cshtml
@{
    ViewData["Title"] = "Create RPM Avatar";
}

<style>
    .frame {
        width: 100%;
        min-height: 900px;
        margin: 0;
        font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;
        padding: 0px;
        font-size: 14px;
        border: none;
    }

    ::-webkit-scrollbar {
        display: none;
    }
</style>

<div class="row w-100" style="margin: 0px;">
    <div class="col-12 w-100">
        <iframe id="frame" class="frame no_scrollbar" style="margin: 0px;" allow="camera *; microphone *; clipboard-write"></iframe>
    </div>
</div>

<script>
    const subdomain = 'demo'; // Replace with your custom subdomain
    const frame = document.getElementById('frame');

    frame.src = `https://${subdomain}.readyplayer.me/avatar?frameApi`;

    window.addEventListener('message', subscribe);
    document.addEventListener('message', subscribe);

    function subscribe(event) {
        const json = parse(event);

        if (json?.source !== 'readyplayerme') {
            return;
        }

        // Susbribe to all events sent from Ready Player Me once frame is ready
        if (json.eventName === 'v1.frame.ready') {
            frame.contentWindow.postMessage(
                JSON.stringify({
                    target: 'readyplayerme',
                    type: 'subscribe',
                    eventName: 'v1.**'
                }),
                '*'
            );
        }

        // Get avatar GLB URL
        if (json.eventName === 'v1.avatar.exported') {
            console.log(`Avatar URL: ${json.data.url}`);
            document.getElementById('avatarUrl').innerHTML = `Avatar URL: ${json.data.url}`;
            document.getElementById('frame').hidden = true;
        }

        // Get user id
        if (json.eventName === 'v1.user.set') {
            console.log(`User with id ${json.data.id} set: ${JSON.stringify(json)}`);
        }
    }

    function parse(event) {
        try {
            return JSON.parse(event.data);
        } catch (error) {
            return null;
        }
    }

    function displayIframe() {
        document.getElementById('frame').hidden = false;
    }
</script>

Views/Avatar/Load.cshtml
@{
    ViewData["Title"] = "RPM Avatar Viewer";
    ViewData["Avatar_src"] = "";

    if (TempData["Avatar_src"] != null)
    {
        ViewData["Avatar_src"] = TempData["Avatar_src"].ToString();
    }
}

<style>
  #modelviewer {
    height: 400px;
    width: 100%;
  }
</style>

<div class="row w-100" style="margin: 0px;">
    <div class="col-12 text-center">
        <h1 class="display-4">Avatar Viewer</h1>
    </div>

    <div class="col-12 w-100">
        <model-viewer id="modelviewer" alt="Ready Player Me Avatar"
        src="@ViewData["Avatar_src"]" shadow-intensity="1" camera-controls
        touch-action="pan-y">
    </model-viewer>
    </div>
</div>

Views/Avatar/LoadAvatar.cshtml
@{
    ViewData["Title"] = "RPM Avatar Loader";
}

<div class="row w-100" style="margin: 0px;">
    <div class="col-12 text-center">
      <img height="100px;" src="https://cdn.glitch.global/3354b915-2147-49b3-8927-9feb031cb867/ReadyPlayerMe-Logo.png?v=1681013428100" alt="RPM_logo"/>    
    </div>
    <div class="col-12 text-center">
        <h1 class="display-4">Avatar Loader</h1>
    </div>   
    <div class="col-12" style="padding-top: 60px;">
        <div class="col-12 text-center form-group">
            @using (Html.BeginForm("Load", "Avatar", FormMethod.Post))
            {
                  <div class="d-inline">
                    <input name="avatar_url" type="text" style="height: 42px;" placeholder=".glb Avatar URL" />
                  </div>
                  <div class="d-inline">
                    <button class="btn btn-primary" style="border-color: black;">Load</button>
                  </div>
            }
        </div>
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="row w-100" style="margin: 0px;">
    <div class="col-12 text-center">
        <h1 class="display-4">Immerse GT 2023 - WebAR Avatars</h1>
    </div>

    <div class="col-12 w-100 text-center" style="margin-top: 40px;">
        <div class="d-inline">
            <button onclick="location.href='@Url.Action("Create", "Avatar")'" class="btn btn-primary" style="height: 42px;">Create Avatar</button>
        </div>
        <div class="d-inline">
            <button onclick="location.href='@Url.Action("LoadAvatar", "Avatar")'" class="btn btn-primary" style="height: 42px;">Load Avatar</button>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication</title>

    <!--import Bootstrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAR_Avatars</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Avatar" asp-action="LoadAvatar">Avatar Loader</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <main>
        @RenderBody()
    </main>

    <hr />

    <footer>
        <p style="margin-left: 10px;">&copy; 2023 - ImmerseGT; Project by: Bryan Brown, Corey Townsend, & Mike Norris</p>
    </footer>

    <script type="module" src="https://ajax.googleapis.com/ajax/libs/model-viewer/3.0.1/model-viewer.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>